### ISSUE TITLE
`config.py` file conflicts with other WB

### ISSUE THREAD

**Issue by hasecilu** [alekssadowski95/FreeCAD-Beginner-Assistant#8]
Rename the `config.py` to something like `fba_config.py`

Other old WB  also use the `config.py` file and when trying to load the path from it an error occurs because it tries to load from another file, from another WB, for example, Steel Column.

Not sure if you would want to change to the new style: https://github.com/FreeCAD/freecad.workbench_starterkit

**Comment by alekssadowski95** [comment]
Thank you for checking. Would you like to help with getting this into the addon manager?

**Comment by alekssadowski95** [comment]
Has been resolved. Thank you for submitting the bug report 🥇

**Comment by alekssadowski95** [comment]
Has been resolved. Thank you for submitting the bug report 🥇

**Comment by hasecilu** [comment]
> Thank you for checking. Would you like to help with getting this into the addon manager?

Sure, here it is: https://github.com/FreeCAD/FreeCAD-addons/pull/325

Related #11
